#!/usr/bin/env python3


import cv2
import numpy as np

def main():
    # initial setup
    cam = cv2.VideoCapture(0)
    counter=False

    while True:

        _, image = cam.read()  # get an image from the camera
        image_flip=cv2.flip(image,1)
        background=np.zeros((image.shape[0],image.shape[1],3),dtype=np.uint8)
 
        cv2.circle(background,(int(image.shape[0]/2),int(image.shape[1]/2)),50,(0,0,255),-2)


        cv2.imshow('background',background)


        # print( (background == (0,0,255)).shape)
        # exit()

        if counter:
            image_flip[background == (0,0,255)] = 0 #! joins the circle and the camera image

        cv2.imshow('Imagem', image_flip)

        k=cv2.waitKey(1) & 0xFF

        if k == 27:
            cv2.destroyAllWindows()
            break
        if k == ord('v'):
            counter = not counter
            print('pila')


if __name__ == "__main__":
    main()